server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    remoteip:
      host-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
      port-header: X-Forwarded-Port
  port: 8090
spring:
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/base_project
    username: ${POSTGRES_UNAME:postgres}
    password: ${POSTGRES_PWD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 3000
      connection-timeout: 30000
      idle-timeout: 10000
      max-lifetime: 30000
      leak-detection-threshold: 20000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      format_sql: true
  flyway:
    baseline-on-migrate: false
    enabled: false
mybatis:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mapper/**/*.xml

rsa:
  private-key: classpath:certificates/private-key-new.pem
  public-key: classpath:certificates/public-key-new.pem

custom:
  public-url: https://192.168.150.106:8090/auth/login

logging:
  level:
    org:
      springframework:
        security: TRACE

      apache:
        ibatis: DEBUG
      mybatis:
        spring:
          SqlSessionFactoryBean: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: beans

springdoc:
  swagger-ui:
    path: /v3/api-docs/
    disable-swagger-default-url: true

file.storage.path: /home/eems/documents/

eems:
  encryption:
    properties:
      key: skbgsjdbvsdbksjg
      initVector: ksjdbnvcbgurjgkd
      transformation: AES/CBC/PKCS5Padding
